### PR TITLE
fix MessagageGateway typo

### PR DESCRIPTION
**Pull request by balopat**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@balopat Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-cloud-gcp&pullRequestId=1)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-cloud-gcp&pullRequestId=1) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
obvious fix

**Comment by pivotal-issuemaster** [comment]
@balopat This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by balopat** [comment]
@gregturn, thanks! I made my org memberships with Google public, now the CLA should be fine for consequent PRs.

**Comment by gregturn** [comment]
👍

**Pull request merged**
