### PR TITLE
Updates guide to use spring-cloud-gcp M2

### PR DESCRIPTION
**Pull request by joaoandremartins**

### CODE REVIEW

**Comment by joaoandremartins** [comment]
@gregturn for your review. Thanks!

**Comment by joaoandremartins** [comment]
@meltsufin FYI

**Review by artembilan — APPROVED** [review]

**Review by meltsufin — APPROVED** [review]

**Comment by joaoandremartins** [comment]
@artembilan I'm assuming you closed this issue by lapse?

**Comment by artembilan** [comment]
Sorry, that is copy/paste and auto-close issue feature 😄 

Reopening...

Thank you for the pointer!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-messaging-gcp-pubsub/commit/328941c0faa20fbe4a98791c31f7c2d3823e808a, https://github.com/spring-guides/gs-messaging-gcp-pubsub/commit/04348f92a75a51911059f7d518883fe5fba3d434, and https://github.com/spring-guides/gs-messaging-gcp-pubsub/commit/3ecedf14d6a745df9ea0f1d2763eaeb1b0aa4f0a.

**Pull request closed without merging**
